-- Script to expand field lengths for better data entry
-- Run this script on your QUANLYBENHVIEN database

USE QUANLYBENHVIEN;
GO

-- YSI (Doctor/Nurse) table
ALTER TABLE YSI ALTER COLUMN HOTEN NVARCHAR(100);
ALTER TABLE YSI ALTER COLUMN LOAIYSI NVARCHAR(50);

-- BENHNHAN (Patient) table
ALTER TABLE BENHNHAN ALTER COLUMN HOTEN NVARCHAR(100);
ALTER TABLE BENHNHAN ALTER COLUMN DIACHI NVARCHAR(200);

-- KHOA (Department) table
ALTER TABLE KHOA ALTER COLUMN TENKHOA NVARCHAR(100);

-- DICHVU (Service) table
ALTER TABLE DICHVU ALTER COLUMN TENDICHVU NVARCHAR(100);

-- PHONG (Room) table
ALTER TABLE PHONG ALTER COLUMN TENPHONG NVARCHAR(100);

-- THUOC (Medicine) table
ALTER TABLE THUOC ALTER COLUMN TENTHUOC NVARCHAR(200);
ALTER TABLE THUOC ALTER COLUMN DONVITINH NVARCHAR(50);

-- Note: TENDANGNHAP is Primary Key, cannot alter directly
-- 30 characters is sufficient for username

PRINT 'Field lengths expanded successfully!';
GO
